use chia_protocol::Bytes32;
use chia_puzzle_types::cat::EverythingWithSignatureTailArgs;
use chia_puzzle_types::Memos;
use chia_sdk_driver::{Cat, CatSpend, SpendContext, SpendWithConditions, StandardLayer};
use chia_sdk_types::{announcement_id, Conditions};
use clvmr::NodePtr;

use crate::constants::{dev_fee, dev_fee_puzzle_hash, issuer_pk, Network};
use crate::error::{Error, Result};
use crate::spend::{StandardCoin, UnsignedSpendBundle, CmojoCoin};
use crate::tail::issuer_partial_signature;

const MELT_ANNOUNCEMENT: &[u8] = b"cmojo-melt";
const ANCHOR_ANNOUNCEMENT: &[u8] = b"cmojo-anchor";

/// Parameters for a melt (burn) operation: destroy `melt_amount` mojos of cMojo
/// and release the same number of mojos as ordinary XCH.
pub struct MeltParams {
    /// The cMojo CAT coins to spend, each with the synthetic key controlling its
    /// inner puzzle. The first coin reveals the TAIL.
    pub cmojo_coins: Vec<CmojoCoin>,
    /// Ordinary XCH coins to spend in the same bundle. These "anchor" coins
    /// absorb the mojos freed by the melt and create the XCH payout, because a
    /// CAT coin can only ever create CAT children — never plain XCH.
    pub anchor_coins: Vec<StandardCoin>,
    /// The p2 puzzle hash that should receive the released XCH.
    pub recipient_puzzle_hash: Bytes32,
    /// The p2 puzzle hash that should receive any leftover (unmelted) cMojo.
    pub cat_change_puzzle_hash: Bytes32,
    /// The amount of cMojo to melt, in mojos.
    pub melt_amount: u64,
    /// The network fee, in mojos, paid from the released XCH.
    pub fee: u64,
    pub network: Network,
}

/// Builds the unsigned spend bundle for a melt.
///
/// The first cMojo coin reveals the TAIL with a negative `extra_delta` (computed
/// automatically by [`Cat::spend_all`]), which lets `melt_amount` mojos leave
/// the CAT ring. Those freed mojos are claimed by the anchor coin, which pays
/// them out as XCH (minus the fee). The CAT spend and the anchor spend are bound
/// to each other with a pair of coin announcements.
pub fn build_melt(params: MeltParams) -> Result<UnsignedSpendBundle> {
    if params.melt_amount == 0 {
        return Err(Error::ZeroAmount);
    }
    if params.cmojo_coins.is_empty() {
        return Err(Error::NoCoins("melt"));
    }
    if params.anchor_coins.is_empty() {
        return Err(Error::NoCoins("melt anchor"));
    }

    let cat_total: u64 = params.cmojo_coins.iter().map(|c| c.cat.coin.amount).sum();
    if cat_total < params.melt_amount {
        return Err(Error::InsufficientFunds {
            have: cat_total,
            need: params.melt_amount,
        });
    }
    let cat_change = cat_total - params.melt_amount;

    let anchor_total: u64 = params.anchor_coins.iter().map(|c| c.coin.amount).sum();
    let redeemable = anchor_total
        .checked_add(params.melt_amount)
        .ok_or(Error::ZeroAmount)?;
    // 0.1% dev fee, paid as an XCH output from the released mojos.
    let dev_fee_amount = dev_fee(params.melt_amount);
    let deductions = params
        .fee
        .checked_add(dev_fee_amount)
        .ok_or(Error::ZeroAmount)?;
    if deductions >= redeemable {
        return Err(Error::FeeExceedsRedeemable {
            fee: deductions,
            redeemable,
        });
    }
    let xch_out = redeemable - deductions;

    let mut ctx = SpendContext::new();
    let tail = ctx.curry(EverythingWithSignatureTailArgs::new(issuer_pk()))?;

    let primary_cat_coin_id = params.cmojo_coins[0].cat.coin.coin_id();
    let anchor0_coin_id = params.anchor_coins[0].coin.coin_id();

    // --- CAT spends -------------------------------------------------------
    let mut cat_spends = Vec::with_capacity(params.cmojo_coins.len());
    for (index, cmojo) in params.cmojo_coins.iter().enumerate() {
        let conditions = if index == 0 {
            let mut conditions = Conditions::new().run_cat_tail(tail, NodePtr::NIL);
            if cat_change > 0 {
                let hint = ctx.hint(params.cat_change_puzzle_hash)?;
                conditions =
                    conditions.create_coin(params.cat_change_puzzle_hash, cat_change, hint);
            }
            // Bind the melt to the anchor coin in both directions.
            conditions
                .create_coin_announcement(MELT_ANNOUNCEMENT.to_vec().into())
                .assert_coin_announcement(announcement_id(anchor0_coin_id, ANCHOR_ANNOUNCEMENT))
        } else {
            // Secondary cMojo coins contribute their full value to the melt; the
            // ring announcements that bind them are generated by `spend_all`.
            Conditions::new()
        };

        let p2_spend = StandardLayer::new(cmojo.synthetic_key).spend_with_conditions(&mut ctx, conditions)?;
        cat_spends.push(CatSpend::new(cmojo.cat, p2_spend));
    }
    let cat_outputs = Cat::spend_all(&mut ctx, &cat_spends)?;

    // --- Anchor spends ----------------------------------------------------
    let anchor0 = params.anchor_coins[0];
    let mut anchor0_conditions = Conditions::new()
        .create_coin(params.recipient_puzzle_hash, xch_out, Memos::None)
        .create_coin_announcement(ANCHOR_ANNOUNCEMENT.to_vec().into())
        .assert_coin_announcement(announcement_id(primary_cat_coin_id, MELT_ANNOUNCEMENT));
    if dev_fee_amount > 0 {
        anchor0_conditions =
            anchor0_conditions.create_coin(dev_fee_puzzle_hash(), dev_fee_amount, Memos::None);
    }
    if params.fee > 0 {
        anchor0_conditions = anchor0_conditions.reserve_fee(params.fee);
    }
    StandardLayer::new(anchor0.synthetic_key).spend(&mut ctx, anchor0.coin, anchor0_conditions)?;

    if params.anchor_coins.len() > 1 {
        let bind = announcement_id(anchor0_coin_id, ANCHOR_ANNOUNCEMENT);
        for extra in &params.anchor_coins[1..] {
            let conditions = Conditions::new().assert_coin_announcement(bind);
            StandardLayer::new(extra.synthetic_key).spend(&mut ctx, extra.coin, conditions)?;
        }
    }

    let coin_spends = ctx.take();
    let issuer_signature = issuer_partial_signature(&coin_spends, params.network)?;

    Ok(UnsignedSpendBundle {
        coin_spends,
        issuer_signature,
        cat_outputs,
    })
}
